# Generated by Django 3.2.17 on 2023-02-17 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230217_0242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='lastname',
        ),
    ]
