# Generated by Django 3.2.17 on 2023-02-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230217_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='birthdate',
        ),
        migrations.AddField(
            model_name='artist',
            name='years_active',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
