# Generated by Django 3.2.17 on 2023-02-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230220_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
