# Generated by Django 3.2.17 on 2023-04-25 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20230411_0205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='year_in_school',
            new_name='album_type',
        ),
        migrations.RenameField(
            model_name='friendrequest',
            old_name='accepted_at',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted'), ('PENDING', 'Pending')], default='PENDING', max_length=50),
        ),
    ]
